### ISSUE TITLE
Build Error at end of run. 

### ISSUE THREAD

**Issue by roland-c** [AKSW/RDFUnit#59] opened 2016-01-25 14:34 UTC
When a testrun is completed a build error is thrown. 

[INFO  SimpleTestExecutorMonitor] Test 2366/2367 returned Errors: 0 / Prevalence: 0. Test: rutt:foaf-RDFSDOMAIN-MISS-ce32ce369944d467574430f8a2c9b638b535fa0981634f7176e007322a630a9d
[INFO  SimpleTestExecutorMonitor] Test 2367/2367 returned Errors: 0 / Prevalence: 0. Test: rutt:foaf-RDFSDOMAIN-MISS-892f44da16d3228153e3800c73194f447259e7e01b41f6a7bedf459635fdc446
[ERROR] BUILD ERROR

**Comment by roland-c** [comment] 2016-01-25 14:56
When -o html,ttl is appended to the command the error is gone. So that's a required parameter (in some cases?)

**Comment by jimkont** [comment] 2016-01-25 15:04
`-o html` is the default output format and shoudn't interfere.
Did you close this by using explicit `-o` or for another reason?

**Comment by jimkont** [comment] 2016-01-25 15:12
asking because ATM RDFUnit is under a lot of refactoring and bugs are easy to slip out

**Comment by roland-c** [comment] 2016-01-25 15:49
The build error disappeared when explicit using -o
If -o should be the default option then there is a problem because when omitted the build error is thrown.

**Comment by jimkont** [comment] 2016-01-25 15:57
I cannot reproduce it, can you send me the exact input

**Comment by roland-c** [comment] 2016-01-25 16:09
I cannot find a log entry of it, it just said Build Error as shown above.

**Comment by jimkont** [comment] 2016-01-25 16:24
Meant to send me what exactly you run and get this error

**Comment by roland-c** [comment] 2016-01-25 18:24
Of course:
bin/rdfunit -d http://lod.kb.nl/nbc/ -e http://lod.kb.nl/sparql  -g http://lod.kb.nl/nbc/

**Comment by jimkont** [comment] 2016-01-26 09:01
still cannot reproduce, it runs fine locally
can you send me the log of a failed execution? should be in `rdfunit-validate/log/*`

**Closed** 2016-06-08 10:45 UTC
